apiVersion: v1
kind: Pod
metadata:
  name: yoromy-backend

spec:
  containers:
  - name: yoromy-backend
    image: chivile/yoromy-backend:v2.0
    tty: true
    stdin: true
    ports:
    - containerPort: 5000
      protocol: TCP
    resources:
    command: ["npm", "start"]
    