apiVersion: v1
kind: Pod
metadata:
  name: yoromy-backend

spec:
  containers:
  - name: yoromy-backend
    image: chivile/yoromy-backend
    tty: true
    stdin: true
    ports:
    - containerPort: 5000
      protocol: TCP
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["npm", "start"]
    