apiVersion: v1
kind: Pod
metadata:
  name: yoromy-client

spec:
  containers:
  - name: yoromy-client
    image: chivile/yoromy-client
    tty: true
    stdin: true
    ports:
    - containerPort: 3000
      protocol: TCP
    resources:
    command: ["npm", "start"]
    